import algoritmo_Bresenham
import algoritmo_DDA


arregloX = []
arregloY = []
figura = int(
    input(
        "Eligue la figura que deseas trazar \n1.Cuadrado \n2.Rectangulo \n3.Triangulo \n=>"
    )
)
algoritmo = int(
    input("Eligue el algoritmo con el que deseas trazar \n1.DDA \n2.Bresenham \n=>")
)

if figura == 1 and algoritmo == 1:
    print("Ingresa las coordenadas de partida del cuadrado")
    x1 = int(input("x1: "))
    y1 = int(input("y1: "))
    lado = int(input("Ingrese el tamaño por lado: "))
    algoritmo_DDA.cuadrilatero_DDA(x1, y1, lado)
elif figura == 1 and algoritmo == 2:
    print("Ingresa las coordenadas del cuadrado")
    x1 = int(input("x1: "))
    arregloX.append(x1)
    y1 = int(input("y1: "))
    arregloY.append(y1)
    x2 = int(input("x2: "))
    arregloX.append(x2)
    y2 = int(input("y2: "))
    arregloY.append(y2)
    x3 = int(input("x3: "))
    arregloX.append(x3)
    y3 = int(input("y3: "))
    arregloY.append(y3)
    x4 = int(input("x4: "))
    arregloX.append(x4)
    y4 = int(input("y4: "))
    arregloY.append(y4)
    algoritmo_Bresenham.cuadrilatero_Bresenham(arregloX, arregloY)
    arregloX.clear()
    arregloY.clear()
elif figura == 2 and algoritmo == 1:
    print("Ingresa las coordenadas del rectangulo")
    x1 = int(input("x1: "))
    arregloX.append(x1)
    y1 = int(input("y1: "))
    arregloY.append(y1)
    x2 = int(input("x2: "))
    arregloX.append(x2)
    y2 = int(input("y2: "))
    arregloY.append(y2)
    x3 = int(input("x3: "))
    arregloX.append(x3)
    y3 = int(input("y3: "))
    arregloY.append(y3)
    x4 = int(input("x4: "))
    arregloX.append(x4)
    y4 = int(input("y4: "))
    arregloY.append(y4)
    algoritmo_DDA.rectangulo_DDA(arregloX, arregloY)
    arregloX.clear()
    arregloY.clear()
elif figura == 2 and algoritmo == 2:
    print("Ingresa las coordenadas del rectangulo")
    x1 = int(input("x1: "))
    arregloX.append(x1)
    y1 = int(input("y1: "))
    arregloY.append(y1)
    x2 = int(input("x2: "))
    arregloX.append(x2)
    y2 = int(input("y2: "))
    arregloY.append(y2)
    x3 = int(input("x3: "))
    arregloX.append(x3)
    y3 = int(input("y3: "))
    arregloY.append(y3)
    x4 = int(input("x4: "))
    arregloX.append(x4)
    y4 = int(input("y4: "))
    arregloY.append(y4)
    algoritmo_Bresenham.cuadrilatero_Bresenham(arregloX, arregloY)
    arregloX.clear()
    arregloY.clear()
elif figura == 3 and algoritmo == 1:
    print("Ingresa las coordenadas del triangulo")
    x1 = int(input("x1: "))
    arregloX.append(x1)
    y1 = int(input("y1: "))
    arregloY.append(y1)
    x2 = int(input("x2: "))
    arregloX.append(x2)
    y2 = int(input("y2: "))
    arregloY.append(y2)
    x3 = int(input("x3: "))
    arregloX.append(x3)
    y3 = int(input("y3: "))
    arregloY.append(y3)
    algoritmo_DDA.triangulo_DDA(arregloX, arregloY)
    arregloX.clear()
    arregloY.clear()
elif figura == 3 and algoritmo == 2:
    print("Ingresa las coordenadas del triangulo")
    x1 = int(input("x1: "))
    arregloX.append(x1)
    y1 = int(input("y1: "))
    arregloY.append(y1)
    x2 = int(input("x2: "))
    arregloX.append(x2)
    y2 = int(input("y2: "))
    arregloY.append(y2)
    x3 = int(input("x3: "))
    arregloX.append(x3)
    y3 = int(input("y3: "))
    arregloY.append(y3)
    algoritmo_Bresenham.triangulo_Bresenham(arregloX, arregloY)
    arregloX.clear()
    arregloY.clear()